import { i18n } from '@/i18n-config'
import { Data, IProductInput, IUserInput } from '@/types'
import bcrypt from 'bcryptjs'
import { toSlug } from './utils'

const users: IUserInput[] = [
	{
		name: 'Test Admin',
		email: 'admin@example.com',
		password: bcrypt.hashSync('Admin@1234', 5),
		role: 'Admin',
		address: {
			fullName: 'John Doe',
			street: '111 Main St',
			city: 'New York',
			province: 'NY',
			postalCode: '10001',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'Stripe',
		emailVerified: false,
	},
	{
		name: 'Test User',
		email: 'user@example.com',
		password: bcrypt.hashSync('User@1234', 5),
		role: 'Admin',
		address: {
			fullName: 'John Doe',
			street: '111 Main St',
			city: 'New York',
			province: 'NY',
			postalCode: '10001',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'Stripe',
		emailVerified: false,
	},
	{
		name: 'Jane',
		email: 'jane@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'Jane Harris',
			street: '222 Main St',
			city: 'New York',
			province: 'NY',
			postalCode: '1002',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'Cash On Delivery',
		emailVerified: false,
	},
	{
		name: 'Jack',
		email: 'jack@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'Jack Ryan',
			street: '333 Main St',
			city: 'New York',
			province: 'NY',
			postalCode: '1003',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'PayPal',
		emailVerified: false,
	},
	{
		name: 'Sarah',
		email: 'sarah@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'Sarah Smith',
			street: '444 Main St',
			city: 'New York',
			province: 'NY',
			postalCode: '1005',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'Cash On Delivery',
		emailVerified: false,
	},
	{
		name: 'Michael',
		email: 'michael@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'John Alexander',
			street: '555 Main St',
			city: 'New York',
			province: 'NY',
			postalCode: '1006',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'PayPal',
		emailVerified: false,
	},
	{
		name: 'Emily',
		email: 'emily@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'Emily Johnson',
			street: '666 Main St',
			city: 'New York',
			province: 'NY',
			postalCode: '10001',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'Stripe',
		emailVerified: false,
	},
	{
		name: 'Alice',
		email: 'alice@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'Alice Cooper',
			street: '777 Main St',
			city: 'New York',
			province: 'NY',
			postalCode: '10007',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'Cash On Delivery',
		emailVerified: false,
	},
	{
		name: 'Tom',
		email: 'tom@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'Tom Hanks',
			street: '888 Main St',
			city: 'New York',
			province: 'NY',
			postalCode: '10008',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'Stripe',
		emailVerified: false,
	},
	{
		name: 'Linda',
		email: 'linda@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'Linda Holmes',
			street: '999 Main St',
			city: 'New York',
			province: 'NY',
			postalCode: '10009',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'PayPal',
		emailVerified: false,
	},
	{
		name: 'George',
		email: 'george@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'George Smith',
			street: '101 First Ave',
			city: 'New York',
			province: 'NY',
			postalCode: '10010',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'Stripe',
		emailVerified: false,
	},
	{
		name: 'Jessica',
		email: 'jessica@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'Jessica Brown',
			street: '102 First Ave',
			city: 'New York',
			province: 'NY',
			postalCode: '10011',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'Cash On Delivery',
		emailVerified: false,
	},
	{
		name: 'Chris',
		email: 'chris@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'Chris Evans',
			street: '103 First Ave',
			city: 'New York',
			province: 'NY',
			postalCode: '10012',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'PayPal',
		emailVerified: false,
	},
	{
		name: 'Samantha',
		email: 'samantha@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'Samantha Wilson',
			street: '104 First Ave',
			city: 'New York',
			province: 'NY',
			postalCode: '10013',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'Stripe',
		emailVerified: false,
	},
	{
		name: 'David',
		email: 'david@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'David Lee',
			street: '105 First Ave',
			city: 'New York',
			province: 'NY',
			postalCode: '10014',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'Cash On Delivery',
		emailVerified: false,
	},
	{
		name: 'Anna',
		email: 'anna@example.com',
		password: bcrypt.hashSync('123456', 5),
		role: 'User',
		address: {
			fullName: 'Anna Smith',
			street: '106 First Ave',
			city: 'New York',
			province: 'NY',
			postalCode: '10015',
			country: 'USA',
			phone: '123-456-7890',
		},
		paymentMethod: 'PayPal',
		emailVerified: false,
	},
]

const products: IProductInput[] = [
	{
		name: 'Giorgio Armani Mens Slim-fit Long-Sleeve Shirt',
		slug: toSlug('Giorgio Armani Mens Slim-fit Long-Sleeve Shirt'),
		category: 'Shirts',
		images: [
			'/images/p11-1.avif',
			'/images/p11-2.webp',
			'/images/p11-3.avif',
			'/images/p11-4.avif',
			'/images/p11-5.avif',
			'/images/p11-6.webp',
		],
		tags: ['new-arrival'],
		isPublished: true,
		price: 29.99,
		listPrice: 0,
		brand: 'Giorgio Armani',
		avgRating: 4.71,
		numReviews: 7,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 2 },
			{ rating: 5, count: 5 },
		],
		numSales: 12,
		countInStock: 11,
		description:
			'Giorgio Armani embraces minimalism with this scaled-back shirt, whosesimple long-sleeved profile speaks for itself. The versatility of this design – a fixture in countless wardrobes –can’t be overstated, as it seamlessly keeps up with both the smart and casual players that currently dominate your rotation.',
		sizes: ['S', 'M', 'L', 'XL', 'XXL'],
		colors: ['white', 'Red', 'Black', 'navy'],

		reviews: [],
	},
	{
		name: 'Polo Ralph Lauren Long-Sleeve Pima Cotton Shirt',
		slug: toSlug('Polo Ralph Lauren Long-Sleeve Pima Cotton Shirt'),
		category: 'Shirts',
		images: [
			'/images/p12-1.avif',
			'/images/p12-2.avif',
			'/images/p12-3.avif',
			'/images/p12-4.avif',
			'/images/p12-5.avif',
			'/images/p12-6.avif',
		],
		tags: ['featured'],
		isPublished: true,
		price: 44.99,
		listPrice: 0,
		brand: 'Polo Ralph Lauren',
		avgRating: 4.2,
		numReviews: 10,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		numSales: 29,
		countInStock: 12,
		description:
			"A simple silhouette merged with Polo Ralph Lauren's elevated sartorial style, this long-sleeved T-shirt is adorned with an intricately embroidered iconic Polo Pony. Crafted from luxuriously soft Pima cotton, it captures the label’s all-American spirit when worn under a checked shirt",

		sizes: ['S', 'M', 'L', 'XL', 'XXL'],
		colors: ['Navy', 'white', 'Black', 'red'],

		reviews: [],
	},
	{
		name: "Homme Issey Miyake Men's Long-Sleeve Pleated Shirt",
		slug: toSlug('Homme Issey Miyake Men Long-Sleeve Pleated Shirt'),
		category: 'Shirts',
		brand: 'Homme Issey Miyake',
		images: [
			'/images/p13-1.avif',
			'/images/p13-2.avif',
			'/images/p13-3.avif',
			'/images/p13-4.avif',
			'/images/p13-5.avif',
			'/images/p13-6.webp',
		],
		tags: ['best-seller'],
		isPublished: true,
		price: 74.99,
		listPrice: 99.99,
		avgRating: 4,
		numReviews: 12,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 2 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		numSales: 55,
		countInStock: 13,
		description:
			"A pared-back aesthetic is married with precise pleating to create this impeccable top from Homme Plissé Issey Miyake. The Japanese label fuses over 30 years' worth of technical know-how with progressive, modern-day details to create a fluid silhouette. Note how the pleats lend a sense of movement to an otherwise humble wardrobe staple.  How to wear Harrods: Style with tailored trousers, sneakers and a shoulder bag.",
		sizes: ['S', 'M', 'L', 'XL'],
		colors: ['Black', 'White', 'Green'],

		reviews: [],
	},
	{
		name: 'Comme Des Garcons Play Heart Logo striped Shirt',
		slug: toSlug('Comme Des Garcons Play Heart Logo striped Shirt'),
		category: 'Shirts',
		brand: 'Comme Des Garcons Play',
		images: [
			'/images/p14-1.avif',
			'/images/p14-2.avif',
			'/images/p14-3.avif',
			'/images/p14-4.avif',
			'/images/p14-5.avif',
			'/images/p14-6.avif',
		],
		tags: ['todays-deal'],
		isPublished: true,
		price: 26.99,
		listPrice: 46.99,
		avgRating: 3.85,
		numReviews: 14,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		numSales: 54,
		countInStock: 14,
		description:
			"Among the kaleidoscope of prints in the oeuvre of Rei Kawakubo's work at Comme des Garçons, you'll find a recurring penchant for gingham, polka dots and stripes, which likely represent a reference to Rei Kawakubo's first childhood memories of fashion in the early 1950s. Here, the designer's Comme des Garçons PLAY line offers up a striped rendition of its iconic heart-embellished T-shirt, a year-round streetwear staple in its collections.",
		sizes: ['S', 'M', 'L', 'XL', 'XXL'],
		colors: ['Blue', 'Red', 'Black'],

		reviews: [],
	},
	{
		name: "Ralph Lauren Men's Slim Fit Long-Sleeve Cotton Plaid Rollneck Top Shirt",
		slug: toSlug(
			"Ralph Lauren Men's Slim Fit Long-Sleeve Cotton Plaid Rollneck Top Shirt",
		),
		category: 'Shirts',
		brand: 'Ralph Lauren',
		images: [
			'/images/p15-1.avif',
			'/images/p15-2.avif',
			'/images/p15-3.avif',
			'/images/p15-4.avif',
			'/images/p15-5.avif',
			'/images/p15-6.avif',
		],
		tags: ['new-arrival', 'featured'],
		isPublished: true,
		price: 29.99,
		listPrice: 35.99,
		avgRating: 3.66,
		numReviews: 15,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		numSales: 54,
		countInStock: 15,
		description:
			'Designing for your golfing pursuits, RLX Ralph Lauren delivers all you need to perform on the course at the most stylish level. This rollneck top conjures up the best of the brand: crafted from cotton for breathable wearability, this piece is imbued with a heritage touch thanks to its Scottish-inspired plaid motif.',
		sizes: ['S', 'M', 'L', 'XL'],
		colors: ['Green', 'Red'],

		reviews: [],
	},
	{
		name: 'Dolce&Gabbana Mens Long-Sleeve Cotton Henley Shirt',
		slug: toSlug('Dolce&Gabbana Mens Long-Sleeve Cotton Henley Shirt'),
		category: 'Shirts',
		brand: 'Dolce&Gabbana',
		images: [
			'/images/p16-1.avif',
			'/images/p16-2.avif',
			'/images/p16-3.avif',
			'/images/p16-4.webp',
			'/images/p16-5.avif',
		],
		tags: ['best-seller', 'todays-deal'],
		isPublished: true,
		price: 25.99,
		listPrice: 32.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 16,
		numSales: 56,
		description:
			'For its latest collection, Dolce&Gabbana lets simple, yet carefully crafted, garments take centre stage. This long-sleeved T-shirt is a timeless addition to any wardrobe, thanks to its crisp cotton finish, while the contrasting embroidery subtly nods to the piece’s origins.',
		sizes: ['S', 'M', 'L', 'XL'],
		colors: ['White', 'Black', 'Blue'],

		reviews: [],
	},
	{
		name: 'Polo Ralph Lauren Mens Short-Sleeve Cotton Slim-Fit Shirt',
		slug: toSlug('Polo Ralph Lauren Mens Short-Sleeve Cotton Slim-Fit Shirt'),
		category: 'Shirts',
		brand: 'Polo Ralph Lauren',
		images: [
			'/images/p17-1.avif',
			'/images/p17-2.webp',
			'/images/p17-3.avif',
			'/images/p17-4.avif',
			'/images/p17-5.avif',
			'/images/p17-6.avif',
		],
		tags: ['best-seller', 'todays-deal'],
		isPublished: true,
		price: 25.99,
		listPrice: 32.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 16,
		numSales: 56,
		description:
			'Fans and critics will be well aware of Polo Ralph Lauren’s pride and joy: the polo shirt. Throughout the brand’s 50-year history, countless iterations have come and gone, but the classic polo you see here is its quintessence. First introduced in 1972 and now offered in a slim-fitting rendition, it makes for a versatile addition to your everyday edit.',
		sizes: ['S', 'M', 'L', 'XL'],
		colors: ['Blue', 'White', 'Black'],

		reviews: [],
	},
	{
		name: 'Our Legacy Mens Long-Sleeve Cotton Stripe Shirt',
		slug: toSlug('Our Legacy Mens Long-Sleeve Cotton Stripe Shirt'),
		category: 'Shirts',
		brand: 'Our Legacy',
		images: [
			'/images/p18-1.avif',
			'/images/p18-2.avif',
			'/images/p18-3.avif',
			'/images/p18-4.avif',
			'/images/p18-5.avif',
			'/images/p18-6.avif',
		],
		tags: ['best-seller', 'todays-deal'],
		isPublished: true,
		price: 29.99,
		listPrice: 39.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 16,
		numSales: 56,
		description:
			'Our Legacy is a Swedish label that reworks wardrobe essentials with a refined approach, favouring classic shapes with lived-in details. This long-sleeve stripe T-shirt captures that mission perfectly, with a relaxed boxy cut and a vintage-faded stripe that looks softly worn from the first wear, making it feel instantly familiar and effortlessly cool.',
		sizes: ['S', 'M', 'L', 'XL'],
		colors: ['Blue', 'White', 'Gray'],

		reviews: [],
	},
	{
		name: 'Emporio Armani Mens Short-Sleeve Cotton Stripe Shirt',
		slug: toSlug('Emporio Armani Mens Short-Sleeve Cotton Stripe Shirt'),
		category: 'Shirts',
		brand: 'Emporio Armani',
		images: [
			'/images/p19-1.avif',
			'/images/p19-2.avif',
			'/images/p19-3.avif',
			'/images/p19-4.avif',
			'/images/p19-5.avif',
			'/images/p19-6.avif',
		],
		tags: ['best-seller', 'todays-deal'],
		isPublished: true,
		price: 25.99,
		listPrice: 32.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 16,
		numSales: 56,
		description:
			'Constructed from a smooth cotton jersey, this Emporio Armani T-shirt offers a substantial drape that holds its boxy shape while remaining breathable. The logo appliqué bridges the gap between classic Ivy League styles and Italian casual-wear, making it an elevated choice for daily ensembles.',
		sizes: ['S', 'M', 'L', 'XL'],
		colors: ['Green', 'Red'],

		reviews: [],
	},
	{
		name: 'Burberry Mens Short-Sleeve Cotton Check-Pocket Shirt',
		slug: toSlug('Burberry Mens Short-Sleeve Cotton Check-Pocket Shirt'),
		category: 'Shirts',
		brand: 'Burberry',
		images: [
			'/images/p20-1.avif',
			'/images/p20-2.avif',
			'/images/p20-3.avif',
			'/images/p20-4.avif',
		],
		tags: ['best-seller', 'todays-deal'],
		isPublished: true,
		price: 29.99,
		listPrice: 44.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 18,
		numSales: 62,
		description:
			'Whatever garment it dons, the Burberry Check is an instantly recognisable ode to Burberry’s heritage, with its origins dating back to the 1920s. Here, it can be spotted to the chest pocket of this cotton T-shirt, creating an ultimately versatile essential with a proud pop of fashion history.',
		sizes: ['S', 'M', 'L', 'XL'],
		colors: ['Black', 'White'],

		reviews: [],
	},

	// !!!Jeans
	{
		name: 'Jacob Cohen Stripe-Trim Slim Jeans',
		slug: toSlug('Jacob Cohen Stripe-Trim Slim Jeans'),
		category: 'Jeans',
		brand: 'Jacob Cohen',
		images: [
			'/images/p21-1.avif',
			'/images/p21-2.avif',
			'/images/p21-3.avif',
			'/images/p21-4.avif',
			'/images/p21-5.avif',
			'/images/p21-6.avif',
		],
		tags: ['new-arrival'],
		isPublished: true,
		price: 95.34,
		listPrice: 0,
		avgRating: 4.71,
		numReviews: 7,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 2 },
			{ rating: 5, count: 5 },
		],
		countInStock: 54,
		numSales: 21,
		description:
			"A pair of reliable jeans is a must have in every man's collection – so why not invest in the tailoring expertise of Jacob Cohën? These comfort-stretch Nick jeans are rendered in a classic faded wash and shaped to a slim silhouette for a timeless look and feel.",
		sizes: ['30Wx30L', '32Wx30L', '32Wx32L'],
		colors: ['Blue', 'Black', 'Grey'],

		reviews: [],
	},
	{
		name: 'Dolce&Gabbana mens Velvet Slim Jeans',
		slug: toSlug('Dolce&Gabbana mens Velvet Slim Jeans'),
		category: 'Jeans',
		brand: 'Dolce&Gabbana',
		images: [
			'/images/p22-1.avif',
			'/images/p22-2.avif',
			'/images/p22-3.avif',
			'/images/p22-4.avif',
			'/images/p22-5.avif',
		],
		tags: ['featured'],
		isPublished: true,
		price: 69.99,
		listPrice: 99.99,
		avgRating: 4.2,
		numReviews: 10,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 22,
		numSales: 54,
		description:
			"Velvet has long since been renowned for its quality and in the hands of Dolce&Gabbana, this is multiplied tenfold. They have been made in Italy with a slim fit that'll remain timeless and flattering after countless seasons of style and have seamless slip pockets as their only decoration. Style them with a pair of chunky boots.",
		sizes: ['30Wx30L', '32Wx30L', '32Wx32L'],
		colors: ['Black', 'Green'],

		reviews: [],
	},
	{
		name: 'Citizens Of Humanity Adler Tapered Slim Jeans',
		slug: toSlug('Citizens Of Humanity Adler Tapered Slim Jeans'),
		category: 'Jeans',
		brand: 'Citizens Of Humanity',
		images: [
			'/images/p23-1.avif',
			'/images/p23-2.avif',
			'/images/p23-3.avif',
			'/images/p23-4.avif',
			'/images/p23-5.avif',
			'/images/p23-6.avif',
		],
		tags: ['best-seller'],
		isPublished: true,
		price: 38.9,
		listPrice: 45,
		avgRating: 4,
		numReviews: 12,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 2 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 23,
		numSales: 54,
		description:
			"Crafted from the brand's innovative Perform denim, the Adler jeans from Citizens of Humanity shine a light on precisely why the label is trusted with our everyday staples. Showcasing a classic rise and a slim-fit silhouette, the pair eases into a tapered leg that's ideal for chunky boots or sneakers.",
		sizes: ['30Wx30L', '32Wx30L', '32Wx32L'],
		colors: ['Grey', 'Blue'],

		reviews: [],
	},
	{
		name: 'Jacob Cohen Stretch Corduroy Bard Slim Jeans',
		slug: toSlug('Jacob Cohen Stretch Corduroy Bard Slim Jeans'),
		category: 'Jeans',
		brand: 'Jacob Cohen',
		images: [
			'/images/p24-1.avif',
			'/images/p24-2.avif',
			'/images/p24-3.avif',
			'/images/p24-4.avif',
			'/images/p24-5.avif',
			'/images/p24-6.avif',
		],
		tags: ['todays-deal'],
		isPublished: true,
		price: 69.99,
		listPrice: 100,
		avgRating: 3.85,
		numReviews: 14,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 24,
		numSales: 53,
		description:
			'Jacob Cohën’s Bard jeans are cut from stretch corduroy in a slim fit that sharpens their profile without compromising comfort. Designed for all-day wear, they offer a rich tactile experience while maintaining a sense of ease and convenience thanks to the flexible fabric.',
		sizes: ['30Wx30L', '32Wx30L', '32Wx32L'],
		colors: ['Blue', 'Grey'],

		reviews: [],
	},
	{
		name: 'Jacob Cohen Stripe-Trim Nick Slim Jeans Indigo Wash',
		slug: toSlug('Jacob Cohen Stripe-Trim Nick Slim Jeans Indigo Wash'),
		category: 'Jeans',
		brand: 'Jacob Cohen',
		images: [
			'/images/p25-1.avif',
			'/images/p25-2.avif',
			'/images/p25-3.avif',
			'/images/p25-4.avif',
			'/images/p25-5.avif',
			'/images/p25-6.avif',
		],
		tags: ['new-arrival', 'featured'],
		isPublished: true,
		price: 95.34,
		listPrice: 0,
		avgRating: 3.66,
		numReviews: 15,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 25,
		numSales: 48,
		description:
			"A pair of reliable jeans is a must have in every man's collection – so why not invest in the tailoring expertise of Jacob Cohën? These comfort-stretch Nick jeans are rendered in a classic faded blackwash and shaped to a slim silhouette for a timeless look and feel.",
		sizes: ['30Wx30L', '32Wx30L', '32Wx32L', '34Wx32L'],
		colors: ['Blue', 'Grey'],

		reviews: [],
	},
	{
		name: 'Jacob Cohen High-Rise Slim Jeans',
		slug: toSlug('Jacob Cohen High-Rise Slim Jeans'),
		category: 'Jeans',
		brand: 'Jacob Cohen',
		images: [
			'/images/p26-1.avif',
			'/images/p26-2.avif',
			'/images/p26-3.avif',
			'/images/p26-4.avif',
			'/images/p26-5.avif',
			'/images/p26-6.avif',
		],
		tags: ['best-seller', 'todays-deal'],
		isPublished: true,
		price: 81.78,
		listPrice: 149.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 26,
		numSales: 48,
		description:
			"Handmade in the Veneto region of Northern Italy, these slim-fit jeans boast a slightly higher rise than the original, while still embodying the quality and attention to detail expected from Jacob Cohën. They're imagined in washed black and punctuated by both the signature haircalf patch to the reverse and a stitched initial to the coin pocket, making a classic addition to your denim repertoire.",
		sizes: ['30Wx30L', '32Wx30L', '32Wx32L', '34Wx32L'],
		colors: ['Blue', 'Grey', 'Black'],

		reviews: [],
	},
	{
		name: 'Polo Ralph Lauren Sullivan Slim Jeans',
		slug: toSlug('Polo Ralph Lauren Sullivan Slim Jeans'),
		category: 'Jeans',
		brand: 'Polo Ralph Lauren',
		images: [
			'/images/p27-1.avif',
			'/images/p27-2.avif',
			'/images/p27-3.avif',
			'/images/p27-4.avif',
			'/images/p27-5.avif',
			'/images/p27-6.avif',
		],
		tags: ['best-seller', 'todays-deal'],
		isPublished: true,
		price: 89.99,
		listPrice: 149.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 36,
		numSales: 58,
		description:
			"These Polo Ralph Lauren jeans employ the label's signature slim fit, sitting snugly across the thighs with a gradual tapering of the leg. Presented in solid denim, the slight stretch ensures day-to-night comfort in your everyday life.",
		sizes: ['30Wx30L', '32Wx30L', '32Wx32L', '34Wx32L'],
		colors: ['Blue', 'Grey'],

		reviews: [],
	},
	{
		name: 'Page Corduroy Federal Slim-Straight Jeans',
		slug: toSlug('Page Corduroy Federal Slim-Straight Jeans'),
		category: 'Jeans',
		brand: 'Page Corduroy Federal ',
		images: [
			'/images/p28-1.avif',
			'/images/p28-2.avif',
			'/images/p28-3.avif',
			'/images/p28-4.avif',
			'/images/p28-5.avif',
			'/images/p28-6.avif',
		],
		tags: ['best-seller', 'todays-deal'],
		isPublished: true,
		price: 69.99,
		listPrice: 149.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 26,
		numSales: 58,
		description:
			'As every gentleman knows, corduroy trousers are a classic menswear staple, and the Federal offering from PAIGE is a timeless pair. Crafted from super-soft micro-corduroy with the perfect amount of stretch for the most comfortable fit, the design is cut to the brand’s contemporary slim-straight silhouette for optimum versatility.',
		sizes: ['30Wx30L', '32Wx30L', '32Wx32L', '34Wx32L'],
		colors: ['Brown', 'Navy', 'Black'],

		reviews: [],
	},
	{
		name: 'BOSS Stretch-Denim Slim Jeans',
		slug: toSlug('BOSS Stretch-Denim Slim Jeans'),
		category: 'Jeans',
		brand: 'BOSS',
		images: [
			'/images/p29-1.avif',
			'/images/p29-2.avif',
			'/images/p29-3.avif',
			'/images/p29-4.avif',
			'/images/p29-5.avif',
			'/images/p29-6.avif',
		],
		tags: ['best-seller'],
		isPublished: true,
		price: 89.99,
		listPrice: 149.99,
		avgRating: 4,
		numReviews: 12,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 2 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 23,
		numSales: 54,
		description:
			'Denim may be inherently linked to the casualness of the off-duty wardrobe, but it may as well find its way into smarter edits, at least when BOSS has something to say about it. The label finesses these slim jeans with sartorial precision from stretch-enriched coloured denim to pair with just about any top in your arsenal.',
		sizes: ['30Wx30L', '32Wx30L', '32Wx32L'],
		colors: ['Beige', 'Black', 'Blue', 'Green'],

		reviews: [],
	},

	// !!!!Watches
	{
		name: 'IWC Schaffhausen Stainless Steel Portofino Chronograph Watch',
		slug: toSlug(
			'IWC Schaffhausen Stainless Steel Portofino Chronograph Watch',
		),
		category: 'Wrist Watches',
		brand: 'IWC',
		images: [
			'/images/p31-1.avif',
			'/images/p31-2.avif',
			'/images/p31-3.avif',
			'/images/p31-4.avif',
			'/images/p31-5.avif',
		],
		tags: ['new-arrival'],
		isPublished: true,
		price: 3500.0,
		listPrice: 0,
		avgRating: 4.71,
		numReviews: 7,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 2 },
			{ rating: 5, count: 5 },
		],
		countInStock: 31,
		numSales: 15,
		description:
			'A classic style from IWC Schaffhausen, the Portofino automatic watch is a lesson in beautiful timepieces. Crafted with a sleek stainless steel case that melts into the alligator strap, this exquisite design marries elegant and masculine styles. Detailed with a dark dial and a slim, 39mm casing, this piece is finished with an engraved back that highlights the piece’s 300m water-resistant casing and the design’s name.',
		sizes: ['39mm', '41mm'],
		colors: ['Black', 'Sliver'],

		reviews: [],
	},
	{
		name: 'IWC Schaffhausen Stainless Steel Pilot XVIII Watch 40mm',
		slug: toSlug('IWC Schaffhausen Stainless Steel Pilot XVIII Watch 40mm'),
		category: 'Wrist Watches',
		brand: 'IWC',
		images: [
			'/images/p32-1.avif',
			'/images/p32-2.avif',
			'/images/p32-3.avif',
			'/images/p32-4.avif',
		],
		tags: ['featured'],
		isPublished: true,
		price: 3750.0,
		listPrice: 4000,
		avgRating: 4.2,
		numReviews: 10,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 32,
		numSales: 18,
		description:
			'Rooted in the traditions of horology that combine precision with luxurious hand-craftsmanship, IWC Schaffhausen nonetheless keeps its designs up to the minute with a focus on innovation and sustainability. Whether in the skies or treading terra firma, the Pilot’s collection takes inspiration from the beginnings of aviation, where the challenging conditions of the cockpit and protective uniforms required an enlarged winding crown for gloved fingers to easily grip. The Pilot XVIII watch maintains this feature, combined with large, clear numbers for a simple yet bold finish.',
		sizes: ['38mm', '40mm'],
		colors: ['Black', 'Sliver'],

		reviews: [],
	},
	{
		name: 'IWC Schaffhausen Stainless Steel Portofino Automatic Watch',
		slug: toSlug('IWC Schaffhausen Stainless Steel Portofino Automatic Watch'),
		category: 'Wrist Watches',
		brand: 'IWC',
		images: [
			'/images/p33-1.avif',
			'/images/p33-2.avif',
			'/images/p33-3.avif',
			'/images/p33-4.avif',
			'/images/p33-5.avif',
			'/images/p33-6.avif',
		],
		tags: ['best-seller'],
		isPublished: true,
		price: 3250.0,
		listPrice: 0,
		avgRating: 4,
		numReviews: 12,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 2 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 33,
		numSales: 19,
		description:
			'The sun-soaked Italian Riviera inspired IWC Schaffhausen’s Portofino watch collection. Calling on the relaxed glamour of the elite hot-spot, the brand creates a design that feels utterly timeless – note the white dial and ageless silver-plated, stainless steel case of this iteration, for example, complete with sea-blue hands and numerals. Originally introduced in 2003, it’s one of the Swiss manufacturer’s most popular timepieces, housing a 25-jewel automatic movement that performs as exceptionally as you’d expect of the revered watchmaker.',
		sizes: ['39mm', '41mm'],
		colors: ['Blue', 'Green', 'Black'],
		reviews: [],
	},
	{
		name: 'IWC Schaffhausen Yellow Gold Portugieser Chronograph Watch',
		slug: toSlug('IWC Schaffhausen Yellow Gold Portugieser Chronograph Watch'),
		category: 'Wrist Watches',
		brand: 'IWC',
		images: ['/images/p34-1.avif', '/images/p34-2.avif', '/images/p34-3.avif'],
		tags: ['todays-deal'],
		isPublished: true,
		price: 9999.99,
		listPrice: 15500.0,
		avgRating: 3.85,
		numReviews: 14,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 10,
		numSales: 14,
		description:
			"Among the many styles in IWC Schaffhausen's repertoire, the Portugieser Chronograph watch stands out as one of the most iconic. It's a design that has been considered perfect since its inception in the 1990s; simply put, there's no need to edit its elegant, functional dial or slender Feuille hands – features that serve as a reminder of the model's origins as a nautical precision instrument. The size of the case is 41mm to fit most wrists, while the slim bezel gives the impression of wearing a much larger watch.",
		sizes: ['39mm', '41mm'],
		colors: ['Gold', 'Sliver'],
		reviews: [],
	},
	{
		name: 'IWC Schaffhausen Ceramic Ingenieur Automatic Watch 42mm',
		slug: toSlug('IWC Schaffhausen Ceramic Ingenieur Automatic Watch 42mm'),
		category: 'Wrist Watches',
		brand: 'IWC',
		images: [
			'/images/p35-1.avif',
			'/images/p35-2.avif',
			'/images/p35-3.avif',
			'/images/p35-4.avif',
		],
		tags: ['new-arrival', 'featured'],
		isPublished: true,
		price: 9999.99,
		listPrice: 15900.0,
		avgRating: 3.66,
		numReviews: 15,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 25,
		numSales: 11,
		description:
			'A timeless design with minimalist detailing, IWC Schaffhausen’s Ingenieur Automatic watch is a classic three-hand timepiece, enhanced by a thicker bezel with screw details and a dial featuring a striking crosshatched texture. This ceramic model – crafted from black zirconium oxide ceramic – is exceptionally hard and scratch-resistant, finished with a combination of satin finishing, sandblasting and polishing, techniques that can only be executed with diamond-tipped tools.',
		sizes: ['40mm', '42mm'],
		colors: ['Black', 'Sliver'],

		reviews: [],
	},
	{
		name: 'IWC Schaffhausen White Gold Portugieser Automatic Watch',
		slug: toSlug('IWC Schaffhausen White Gold Portugieser Automatic Watch'),
		category: 'Wrist Watches',
		brand: 'IWC',
		images: [
			'/images/p36-1.avif',
			'/images/p36-2.avif',
			'/images/p36-3.avif',
			'/images/p36-4.avif',
			'/images/p36-5.avif',
			'/images/p36-6.webp',
		],
		tags: ['best-seller', 'todays-deal'],
		isPublished: true,
		price: 8999.99,
		listPrice: 15500.0,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 36,
		numSales: 29,
		description:
			'IWC Schaffhausen demonstrates first-hand what makes a timepiece iconic with its Portugieser Automatic watch. The elegantly athletic model is more than a sought-after design; it forms part of one of the Swiss brand’s most prestigious collections, which had its start in the 1930s. The story goes that IWC was approached by two Portuguese businessmen requesting a wristwatch with the same precision as marine chronometers and, as a result, the first Portugieser was born. Today, the style remains one of horology’s finest and you can analyse its legendary, robust movement at work thanks to the sapphire-glass case back of this modern rendition.',
		sizes: ['38mm', '40mm'],
		colors: ['Blue', 'Sliver', 'Black'],

		reviews: [],
	},

	{
		name: 'IWC Schaffhausen Stainless Steel Portofino Complete Calendar Watch 41mm',
		slug: toSlug(
			'IWC Schaffhausen Stainless Steel Portofino Complete Calendar Watch 41mm',
		),
		category: 'Wrist Watches',
		brand: 'IWC',
		images: [
			'/images/p37-1.avif',
			'/images/p37-2.avif',
			'/images/p37-3.avif',
			'/images/p37-4.avif',
			'/images/p37-5.avif',
		],
		tags: ['best-seller'],
		isPublished: true,
		price: 6250.0,
		listPrice: 0,
		avgRating: 4,
		numReviews: 12,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 2 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 33,
		numSales: 19,
		description:
			'Introducing the newest member of IWC’s iconic Portofino collection: the Portofino Complete Calendar. Capturing the understated spirit of the original model launched in the ‘80s, this iteration is crafted from stainless steel with a textured leather strap. Two elegant subdials showcase a moonphase complication with days of the week and a full monthly calendar.',
		sizes: ['41mm'],
		colors: ['Blue', 'Green'],
		reviews: [],
	},
	{
		name: 'H. Moser & Cie Stainless Steel Pioneer Centre Seconds Watch 40mm',
		slug: toSlug(
			'H. Moser & Cie Stainless Steel Pioneer Centre Seconds Watch 40mm',
		),
		category: 'Wrist Watches',
		brand: 'H. Moser & Cie',
		images: [
			'/images/p38-1.avif',
			'/images/p38-2.avif',
			'/images/p38-3.avif',
			'/images/p38-4.avif',
			'/images/p38-5.avif',
			'/images/p38-6.avif',
		],
		tags: ['new-arrival'],
		isPublished: true,
		price: 3500.0,
		listPrice: 0,
		avgRating: 4.71,
		numReviews: 7,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 2 },
			{ rating: 5, count: 5 },
		],
		countInStock: 31,
		numSales: 15,
		description:
			'The brand remains one of the few independent, family owned watch manufacturers in existence. For almost two centuries, H. Moser & Cie has been crafting its Swiss timepieces by hand using its own in-house mechanical movements. Balancing a rugged spirit with the label’s striking minimalist aesthetic, the Pioneer watch features a centre seconds hand that glides across the dial – drawing attention to its vibrant fumé dial. The simplicity of this design is underpinned by the complexity of its skeleton case back, which gives a glimpse into the HMC 201 movement.',
		sizes: ['40mm'],
		colors: ['Green', 'Black', 'Sliver'],

		reviews: [],
	},
	{
		name: 'Panerai Stainless Steel Submersible Watch 44mm',
		slug: toSlug('Panerai Stainless Steel Submersible Watch 44mm'),
		category: 'Wrist Watches',
		brand: 'Panerai',
		images: [
			'/images/p39-1.avif',
			'/images/p39-2.avif',
			'/images/p39-3.avif',
			'/images/p39-4.avif',
			'/images/p39-5.avif',
		],
		tags: ['featured'],
		isPublished: true,
		price: 4750.0,
		listPrice: 7900.0,
		avgRating: 4.2,
		numReviews: 10,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 32,
		numSales: 18,
		description:
			'Even at great depths, Panerai ensures first-rate visibility. For adventurous explorers – in the ocean and otherwise – the Submersible watch from Panerai is the gold standard. After all, the formidable label manufactured timepieces for the Italian Navy in the ‘50s, developing watches known for their unparalleled luminosity in darkness. This model boasts high-tech materials, strong water resistance (at 300 metres) and a unidirectional rotating bezel to calculate immersion time.',
		sizes: ['42mm', '44mm'],
		colors: ['Green', 'Black', 'Sliver'],

		reviews: [],
	},

	// !!! Shoes
	{
		name: 'TODS Suede Sportiva 59L Sneakers',
		slug: toSlug('TODS Suede Sportiva 59L Sneakers'),
		category: 'Shoes',
		brand: 'TODS',
		images: [
			'/images/p41-1.avif',
			'/images/p41-2.avif',
			'/images/p41-3.avif',
			'/images/p41-4.avif',
		],
		tags: ['new-arrival'],
		isPublished: true,
		price: 199.99,
		listPrice: 0,
		avgRating: 4.71,
		numReviews: 7,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 2 },
			{ rating: 5, count: 5 },
		],
		countInStock: 41,
		numSales: 48,
		description:
			'A label synonymous with expert craftsmanship and luxurious allure – Tod’s deserves a place in every accomplished wardrobe. First established in the 1920s, the Italian label has since branched into contemporary footwear with exemplary results. The Sportiva sneakers boast a chic silhouette, with a chunky sole adding a street style-inspired edge and the rubber composition providing comfortable cushioning for ease of wear from morning till night.',
		sizes: ['8', '9', '10', '11'],
		colors: ['White', 'Black', 'Grey'],

		reviews: [],
	},
	{
		name: 'TOM FORD Suede Archer Sneakers',
		slug: toSlug('TOM FORD Suede Archer Sneakers'),
		category: 'Shoes',
		brand: 'TOM FORD',
		images: [
			'/images/p42-1.avif',
			'/images/p42-2.avif',
			'/images/p42-3.avif',
			'/images/p42-4.avif',
		],
		tags: ['featured'],
		isPublished: true,
		price: 199.99,
		listPrice: 599.99,
		avgRating: 4.2,
		numReviews: 10,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 42,
		numSales: 50,
		description:
			'Crafted from supple suede with the clean precision TOM FORD is known for, the Archer sneakers strike a balance between relaxed and refined. Ideal for city strolls abroad or spontaneous coffee dates, they’re proof that comfort doesn’t have to compromise on character.',
		sizes: ['8', '9', '10', '11'],
		colors: ['Beige', 'Black', 'Grey'],

		reviews: [],
	},
	{
		name: 'Zegna Leather Triple Stitch Sneakers',
		slug: toSlug('Zegna Leather Triple Stitch Sneakers'),
		category: 'Shoes',
		brand: 'Zegna',
		images: [
			'/images/p43-1.avif',
			'/images/p43-2.avif',
			'/images/p43-3.avif',
			'/images/p43-4.avif',
		],
		tags: ['best-seller'],
		isPublished: true,
		price: 99.99,
		listPrice: 0,
		avgRating: 4,
		numReviews: 12,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 2 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 43,
		numSales: 72,
		description:
			'A perfectly sleek silhouette from Italian designer Zegna, the Triple Stitch sneakers draw their name from three crossover laces upon the vamp – capturing the refined aesthetic that the brand is renowned for. Luring you in through the grained leather upper and sumptuous touch of suede trims, this pair will instantly enrich any casual ensemble.',
		sizes: ['8', '9', '10', '11'],
		colors: ['Black', 'Grey'],

		reviews: [],
	},
	{
		name: 'Christian Louboutin Rantulow Orlato Velour Sneakers',
		slug: toSlug('Christian Louboutin Rantulow Orlato Velour Sneakers'),
		category: 'Shoes',
		brand: 'Christian Louboutin',
		images: [
			'/images/p44-1.avif',
			'/images/p44-2.avif',
			'/images/p44-3.avif',
			'/images/p44-4.avif',
			'/images/p44-5.avif',
		],
		tags: ['todays-deal'],
		isPublished: true,
		price: 199.99,
		listPrice: 399.99,
		avgRating: 3.85,
		numReviews: 14,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 44,
		numSales: 42,
		description:
			"Showcasing curved lines, Christian Louboutin's Rantulow Orlato sneakers take inspiration from 1980s low-top basketball sneakers. Updating the classic silhouette with a sumptuous velour finish, the pair is crafted from durable calfskin and is accented with the Maison’s signature on the sole, lending a covetable flash with every step you take.",
		sizes: ['8', '9', '10', '11', '12'],
		colors: ['Brown', 'Black', 'Grey'],

		reviews: [],
	},
	{
		name: 'ON Cloudtilt Trainers',
		slug: toSlug('ON Cloudtilt Trainers'),
		category: 'Shoes',
		brand: 'ON',
		images: [
			'/images/p45-1.avif',
			'/images/p45-2.avif',
			'/images/p45-3.avif',
			'/images/p45-4.avif',
			'/images/p45-5.avif',
			'/images/p45-6.avif',
		],
		tags: ['new-arrival', 'featured'],
		isPublished: true,
		price: 99.95,
		listPrice: 150,
		avgRating: 3.66,
		numReviews: 15,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 45,
		numSales: 64,
		description:
			'Since its inception in 2010, On has made waves in the sportswear scene, particularly with its trainers which feature multiple scientific mechanisms to create better athletic performances. The Cloudtilt trainers are kitted out with CloudTec Phase, an exclusive brand mechanism that assists with high levels of forward motion, as well as super-bouncy cushioning for fast, off-the-mark starts.',
		sizes: ['8', '9', '10', '11'],
		colors: ['White', 'Grey'],

		reviews: [],
	},
	{
		name: 'Zenga Suede Triple Stitch Espadrilles',
		slug: toSlug('Zenga Suede Triple Stitch Espadrilles'),
		category: 'Shoes',
		brand: 'Zenga',
		images: [
			'/images/p46-1.avif',
			'/images/p46-2.avif',
			'/images/p46-3.avif',
			'/images/p46-4.avif',
		],
		tags: ['best-seller', 'todays-deal'],
		isPublished: true,
		price: 199.99,
		listPrice: 299.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 46,
		numSales: 48,
		description:
			'Zegna’s Triple Stitch design has become something of a staple among those in the know, with its signature crossover elastic laces and clean lines. Here, the Italian House translates the soft suede profile atop woven jute soles, creating a refined yet casual espadrille shoe.',
		sizes: ['8', '9', '10', '11'],
		colors: ['Blue', 'Black', 'Grey'],

		reviews: [],
	},
	{
		name: 'Zenga Suede Triple Stitch Sneakers',
		slug: toSlug('Zenga Suede Triple Stitch Sneakers'),
		category: 'Shoes',
		brand: 'Zenga',
		images: [
			'/images/p47-1.avif',
			'/images/p47-2.avif',
			'/images/p47-3.avif',
			'/images/p47-4.avif',
		],
		tags: ['best-seller', 'todays-deal'],
		isPublished: true,
		price: 199.99,
		listPrice: 299.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 46,
		numSales: 48,
		description:
			'A sleek and timeless silhouette from Italian designer Zegna, the Triple Stitch sneakers draw their name from three crossover laces upon the vamp, capturing the refined aesthetic that the brand is renowned for. It’s all about texture when it comes to this pair, with panels of soft suede resulting in a sophisticated yet modern take on an everyday staple.',
		sizes: ['8', '9', '10', '11'],
		colors: ['Black', 'Grey'],

		reviews: [],
	},
	{
		name: 'PRADA Patent Leather-Blend American Cup Sneakers Black',
		slug: toSlug('PRADA Patent Leather-Blend American Cup Sneakers Black'),
		category: 'Shoes',
		brand: 'PRADA',
		images: [
			'/images/p48-1.avif',
			'/images/p48-2.avif',
			'/images/p48-3.avif',
			'/images/p48-4.avif',
			'/images/p48-5.avif',
			'/images/p48-6.avif',
		],
		tags: ['featured'],
		isPublished: true,
		price: 199.99,
		listPrice: 599.99,
		avgRating: 4.2,
		numReviews: 10,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 42,
		numSales: 50,
		description:
			'First created in the Nineties for the Luna Rossa, the Italian sailing team sponsored by Prada, the America’s Cup sneakers are inspired by the oceanic sporting world. Their design unites a seamless combination of breathable nylon and patent leather, while a linear Rossa logo affirms their esteemed origins, making them a triumph of sportsmanship and innovation.',
		sizes: ['8', '9', '10', '11'],
		colors: ['Black'],

		reviews: [],
	},
	{
		name: 'Prada Leather Driving Shoe',
		slug: toSlug('Prada Leather Driving Shoe'),
		category: 'Shoes',
		brand: 'Prada',
		images: [
			'/images/p49-1.avif',
			'/images/p49-2.avif',
			'/images/p49-3.avif',
			'/images/p49-4.avif',
			'/images/p49-5.avif',
			'/images/p49-6.avif',
		],
		tags: ['new-arrival'],
		isPublished: true,
		price: 199.99,
		listPrice: 0,
		avgRating: 4.71,
		numReviews: 7,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 2 },
			{ rating: 5, count: 5 },
		],
		countInStock: 41,
		numSales: 48,
		description:
			"The perfect pairing for the brand's slim summer tailoring. First introduced in 1913 by Mario Prada, the cross-hatch, scratch-resistant texture of Saffiano leather has become synonymous with Prada's sleek aesthetic. Here, the calf leather material is applied to a deconstructed driving loafer, resulting in a completely unique silhouette.",
		sizes: ['8', '9', '10', '11'],
		colors: ['White', 'Black', 'Grey'],

		reviews: [],
	},

	// !!!! Sunglasses
	{
		name: 'Jacques Marie Mage Metal Amelia Aviator Sunglasses',
		slug: toSlug('Jacques Marie Mage Metal Amelia Aviator Sunglasses'),
		category: 'Sunglasses',
		brand: 'Jacques Marie Mage',
		images: [
			'/images/p51-1.avif',
			'/images/p51-2.avif',
			'/images/p51-3.avif',
			'/images/p51-4.avif',
			'/images/p51-5.avif',
		],
		tags: ['new-arrival'],
		isPublished: true,
		price: 199.0,
		listPrice: 0,
		avgRating: 4.71,
		numReviews: 7,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 2 },
			{ rating: 5, count: 5 },
		],
		countInStock: 31,
		numSales: 15,
		description:
			'Designed after classic aviator styles, the Amelia sunglasses from Jacques Marie Mage will become a timeless addition to your accessories edit. Their sleek frame is defined by deep teardrop lenses and Art Deco-inspired details, both of which are part of an intricate 300-step process that creates each pair.',
		sizes: ['Large'],
		colors: ['Black', 'Silver'],

		reviews: [],
	},
	{
		name: 'Jacques Marie Mage Metal Amelia Aviator Sunglasses Gold',
		slug: toSlug('Jacques Marie Mage Metal Amelia Aviator Sunglasses Gold'),
		category: 'Sunglasses',
		brand: 'Jacques Marie Mage',
		images: [
			'/images/p52-1.avif',
			'/images/p52-2.avif',
			'/images/p52-3.avif',
			'/images/p52-4.avif',
			'/images/p52-5.avif',
		],
		tags: ['featured'],
		isPublished: true,
		price: 199.0,
		listPrice: 399.0,
		avgRating: 4.2,
		numReviews: 10,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 32,
		numSales: 18,
		description:
			'Designed after classic aviator styles, the Amelia sunglasses from Jacques Marie Mage will become a timeless addition to your accessories edit. Their sleek frame is defined by deep teardrop lenses and Art Deco-inspired details, both of which are part of an intricate 300-step process that creates each pair.',
		sizes: ['Large'],
		colors: ['Gold', 'Silver'],

		reviews: [],
	},
	{
		name: 'Jacques Marie Mage Tortoiseshell Aspen Aviator Sunglasses',
		slug: toSlug('Jacques Marie Mage Tortoiseshell Aspen Aviator Sunglasses'),
		category: 'Sunglasses',
		brand: 'Jacques Marie Mage',
		images: [
			'/images/p53-1.avif',
			'/images/p53-2.avif',
			'/images/p53-3.avif',
			'/images/p53-4.avif',
			'/images/p53-5.avif',
		],
		tags: ['best-seller'],
		isPublished: true,
		price: 199.0,
		listPrice: 399.0,
		avgRating: 4,
		numReviews: 12,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 2 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 33,
		numSales: 19,
		description:
			"Inspired by 1960s pilot styles, the Aspen sunglasses by Jacques Marie Mage have adrenaline pumping through their frames. Hailing from the brand's Titanium series, this vintage-inspired pair features metal and acetate accents with crescent-shaped gradient lenses for a finish that nods to nostalgic sports silhouettes.",
		sizes: ['Medium'],
		colors: ['Silver', 'Gold'],
		reviews: [],
	},
	{
		name: 'Bottega Veneta BV1305S Green-Tinted Sunglasses',
		slug: toSlug('Bottega Veneta BV1305S Green-Tinted Sunglasses'),
		category: 'Sunglasses',
		brand: 'Bottega Veneta',
		images: [
			'/images/p54-1.avif',
			'/images/p54-2.avif',
			'/images/p54-3.avif',
			'/images/p54-4.avif',
		],
		tags: ['todays-deal'],
		isPublished: true,
		price: 199.99,
		listPrice: 299.0,
		avgRating: 3.85,
		numReviews: 14,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 10,
		numSales: 14,
		description:
			'As sleek as the brand that makes them, these sunglasses from Italian powerhouse Bottega Venetta present as a modern iteration of the timeless Aviator silhouette. Green-tinted lenses pop against the gold-tone frame, creating a fresh feel that will undoubtedly inject some vintage cool into your summer looks.',
		sizes: ['Medium'],
		colors: ['Gold', 'Silver'],
		reviews: [],
	},
	{
		name: 'Cartier Rectangular Sunglasses',
		slug: toSlug('Cartier Rectangular Sunglasses'),
		category: 'Sunglasses',
		brand: 'Cartier',
		images: [
			'/images/p55-1.avif',
			'/images/p55-2.avif',
			'/images/p55-3.avif',
			'/images/p55-4.avif',
		],
		tags: ['new-arrival', 'featured'],
		isPublished: true,
		price: 399.99,
		listPrice: 799.99,
		avgRating: 3.66,
		numReviews: 15,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 25,
		numSales: 31,
		description:
			"The magic of Cartier's sunglasses is that every pair goes well beyond the purpose of sun protection – after all, an accessory can make or break a look. That's why this rectangular iteration features C-shaped details and a debossed logo.",
		sizes: ['Medium', 'Large'],
		colors: ['Gold', 'Silver'],

		reviews: [],
	},
	{
		name: 'Ray-Ban RB3774D Metal Oval Sunglasses',
		slug: toSlug('Ray-Ban RB3774D Metal Oval Sunglasses'),
		category: 'Sunglasses',
		brand: 'Ray-Ban',
		images: [
			'/images/p56-1.avif',
			'/images/p56-2.avif',
			'/images/p56-3.avif',
			'/images/p56-4.avif',
			'/images/p56-5.avif',
			'/images/p56-6.avif',
		],
		tags: ['best-seller', 'todays-deal'],
		isPublished: true,
		price: 99.99,
		listPrice: 199.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 36,
		numSales: 29,
		description:
			'Founded in 1936, Ray-Ban was a pioneer in the realm of luxury eyewear, becoming the go-to for sleek, refined sunglasses with practical eye protection. This pair highlights its expertise through a flattering oval silhouette crafted from gold-tone metal and fixed with 100% UV protection lenses.',
		sizes: ['Medium', 'Large'],
		colors: ['Gold', 'Silver', 'Black'],

		reviews: [],
	},

	{
		name: 'Cartier Rectangular Sunglasses Tortoiseshell',
		slug: toSlug('Cartier Rectangular Sunglasses Tortoiseshell'),
		category: 'Sunglasses',
		brand: 'Cartier',
		images: [
			'/images/p57-1.avif',
			'/images/p57-2.avif',
			'/images/p57-3.avif',
			'/images/p57-4.avif',
		],
		tags: ['best-seller'],
		isPublished: true,
		price: 199.99,
		listPrice: 0,
		avgRating: 4,
		numReviews: 12,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 2 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 33,
		numSales: 19,
		description:
			"The magic of Cartier's sunglasses is that every pair goes well beyond the purpose of sun protection – after all, an accessory can make or break a look. That's why this rectangular iteration features C-shaped details and a debossed logo.",
		sizes: ['Medium', 'Large'],
		colors: ['Silver', 'Black'],
		reviews: [],
	},
	{
		name: 'Jacques Marie Mage Titanium Sun Blue Star Sunglasses',
		slug: toSlug('Jacques Marie Mage Titanium Sun Blue Star Sunglasses'),
		category: 'Sunglasses',
		brand: 'Jacques Marie Mage',
		images: [
			'/images/p58-1.avif',
			'/images/p58-2.avif',
			'/images/p58-3.avif',
			'/images/p58-4.avif',
			'/images/p58-5.avif',
			'/images/p58-6.avif',
		],
		tags: ['new-arrival'],
		isPublished: true,
		price: 199.0,
		listPrice: 0,
		avgRating: 4.71,
		numReviews: 7,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 2 },
			{ rating: 5, count: 5 },
		],
		countInStock: 31,
		numSales: 15,
		description:
			'Jacques Marie Mage tells a story with each shape. Jacques Marie Mage is built on the belief that eyewear should be an artefact: meticulously crafted, culturally informed and rich with story. The Blue Star sunglasses belong to the label’s Yellowstone collection, a line-up that recalls the vast spirit of the American West and the unique ecosystems that define it. Engineered to a pilot-inspired shape, they’re fitted with tinted blue lenses that lend them an atmospheric light.',
		sizes: ['Large'],
		colors: ['Silver'],

		reviews: [],
	},
	{
		name: 'Ray-Ban RB3925 Aviator Max Sunglasses',
		slug: toSlug('Ray-Ban RB3925 Aviator Max Sunglasses'),
		category: 'Sunglasses',
		brand: 'Ray-Ban',
		images: [
			'/images/p59-1.avif',
			'/images/p59-2.avif',
			'/images/p59-3.avif',
			'/images/p59-4.avif',
			'/images/p59-5.avif',
			'/images/p59-6.avif',
		],
		tags: ['new-arrival', 'featured'],
		isPublished: true,
		price: 199.99,
		listPrice: 399.99,
		avgRating: 3.66,
		numReviews: 15,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 25,
		numSales: 31,
		description:
			'A thicker frame takes them to the max. As you’re no doubt aware, there’s one pair of sunglasses that sits larger in the collective fashion mind than all its contemporaries: the classic Ray-Ban Aviators. The style is ubiquitous across the globe, renowned for its iconic and effortlessly cool shape – one that was originally designed for American pilots in 1937. This rendition, named the Aviator Max, introduces a new twist with a thicker frame for a bold touch.',
		sizes: ['Medium', 'Large'],
		colors: ['Gold', 'Silver'],

		reviews: [],
	},

	// !!! Cufflinks
	{
		name: 'Tateossian Sterling Silver and Topaz Graffiato Cufflinks',
		slug: toSlug('Tateossian Sterling Silver and Topaz Graffiato Cufflinks'),
		category: 'Cufflinks',
		brand: 'Tateossian',
		images: [
			'/images/p61-1.avif',
			'/images/p61-2.avif',
			'/images/p61-3.avif',
			'/images/p61-4.avif',
			'/images/p61-5.avif',
			'/images/p61-6.avif',
		],
		tags: ['featured'],
		isPublished: true,
		price: 99.99,
		listPrice: 0,
		avgRating: 4.71,
		numReviews: 7,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 2 },
			{ rating: 5, count: 5 },
		],
		countInStock: 54,
		numSales: 21,
		description:
			'The Graffiato cufflinks are the latest addition to Tateossian’s Classic collection, named after the word scratch in Italian. Imagined in sterling silver with rhodium plating, the textured square design is complete with a topaz at the centre for a hint of sparkle.',
		sizes: ['Standard'],
		colors: ['Silver'],

		reviews: [],
	},
	{
		name: 'Giorgio Armani Sterling Silver Embellished Cufflinks',
		slug: toSlug('Giorgio Armani Sterling Silver Embellished Cufflinks'),
		category: 'Cufflinks',
		brand: 'Giorgio Armani',
		images: [
			'/images/p62-1.avif',
			'/images/p62-2.avif',
			'/images/p62-3.avif',
			'/images/p62-4.avif',
			'/images/p62-5.avif',
		],
		tags: ['new-arrival'],
		isPublished: true,
		price: 99.99,
		listPrice: 199.99,
		avgRating: 4.2,
		numReviews: 10,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 22,
		numSales: 54,
		description:
			"Giorgio Armani and tailoring go hand in hand – and it's not just the suiting the label offers, but all the much-needed finishing touches that create the outfit. Cufflinks are the final piece you add to any formal ensemble, and this pair is embellished with a coloured crystal for a flash of colour on the sleeve.",
		sizes: ['Standard'],
		colors: ['Silver'],

		reviews: [],
	},
	{
		name: 'Cartier Sterling Silver Panthere de Cartier Cufflinks',
		slug: toSlug('Cartier Sterling Silver Panthere de Cartier Cufflinks'),
		category: 'Cufflinks',
		brand: 'Cartier',
		images: [
			'/images/p63-1.avif',
			'/images/p63-2.avif',
			'/images/p63-3.avif',
			'/images/p63-4.avif',
		],
		tags: ['new-arrival'],
		isPublished: true,
		price: 99.99,
		listPrice: 179.99,
		avgRating: 4,
		numReviews: 12,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 2 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 23,
		numSales: 54,
		description:
			"The panther has been associated with Cartier for over a century, with the feline's mysterious nature undeniably alluring. Encapsulated in the ever-popular Panthère de Cartier collection, it features here upon these sterling silver cufflinks, depicted curving around a pool of captivating hawk's eye. Fix them upon shirt cuffs whenever you're in need of a little talismanic protection.",
		sizes: ['Standard'],
		colors: ['Silver'],

		reviews: [],
	},
	{
		name: 'Cartier Sterling Silver Santos de Cartier Cufflinks',
		slug: toSlug('Cartier Sterling Silver Santos de Cartier Cufflinks'),
		category: 'Cufflinks',
		brand: 'Cartier',
		images: [
			'/images/p64-1.avif',
			'/images/p64-2.avif',
			'/images/p64-3.avif',
			'/images/p64-4.avif',
		],
		tags: ['featured'],
		isPublished: true,
		price: 129.99,
		listPrice: 199.99,
		avgRating: 3.85,
		numReviews: 14,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 24,
		numSales: 53,
		description:
			'Cartier belongs at the wrist and the ends of sleeves, emphasised once more by the Santos de Cartier cufflinks – a design that pairs sterling silver with a blue synthetic spinel for added visual appeal. Perfect for accessorising your favourite shirts, this offering also boasts a certain timelessness so often associated with the Maison.',
		sizes: ['Standard'],
		colors: ['Silver'],

		reviews: [],
	},
	{
		name: 'Cartier Yellow Gold LOVE Cufflinks',
		slug: toSlug('Cartier Yellow Gold LOVE Cufflinks'),
		category: 'Cufflinks',
		brand: 'Cartier',
		images: [
			'/images/p65-1.avif',
			'/images/p65-2.avif',
			'/images/p65-3.avif',
			'/images/p65-4.avif',
			'/images/p65-5.avif',
		],
		tags: ['featured'],
		isPublished: true,
		price: 199,
		listPrice: 0,
		avgRating: 3.66,
		numReviews: 15,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 5 },
		],
		countInStock: 25,
		numSales: 48,
		description:
			'When one thinks of Cartier, the LOVE collection likely springs to mind. It was conceptualised by legendary jewellery designer Aldo Cipullo in 1969 and has since become an icon. Now, the symbolic collection introduces these cufflinks, crafted from 18-karat white gold and detailed with the renowned screw detail; secure them to the cuffs of your finest shirt in a suave ode to everlasting LOVE.',
		sizes: ['Standard'],
		colors: ['Gold'],

		reviews: [],
	},
	{
		name: 'Tateossian Sterling Silver and Ruby Square Cufflinks',
		slug: toSlug('Tateossian Sterling Silver and Ruby Square Cufflinks'),
		category: 'Cufflinks',
		brand: 'Tateossian',
		images: [
			'/images/p66-1.avif',
			'/images/p66-2.avif',
			'/images/p66-3.avif',
			'/images/p66-4.avif',
			'/images/p66-5.avif',
			'/images/p66-6.avif',
		],
		tags: ['todays-deal'],
		isPublished: true,
		price: 199.99,
		listPrice: 449.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 26,
		numSales: 38,
		description:
			"With a deep ruby centre that symbolises wisdom and passion, this pair of cufflinks is certain to make any suit dazzle with sartorial elegance. Encapsulating Tateossian's playful side, framed by contrasting sterling silver, they're the perfect gift for the elegant gentleman in your life.",
		sizes: ['Standard'],
		colors: ['Silver'],

		reviews: [],
	},
	{
		name: 'Giorgio Armani Sterling Silver Embellished Cufflinks Crystal',
		slug: toSlug(
			'Giorgio Armani Sterling Silver Embellished Cufflinks Crystal',
		),
		category: 'Cufflinks',
		brand: 'Giorgio Armani',
		images: [
			'/images/p67-1.avif',
			'/images/p67-2.avif',
			'/images/p67-3.avif',
			'/images/p67-4.avif',
			'/images/p67-5.avif',
			'/images/p67-6.avif',
		],
		tags: ['todays-deal'],
		isPublished: true,
		price: 189.99,
		listPrice: 449.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 36,
		numSales: 58,
		description:
			"Giorgio Armani and tailoring go hand in hand – and it's not just the suiting the label offers, but all the much-needed finishing touches that create the outfit. Cufflinks are the final piece you add to any formal ensemble, and this pair is embellished with a coloured crystal for a flash of colour on the sleeve.",
		sizes: ['Standard'],
		colors: ['Silver'],

		reviews: [],
	},
	{
		name: 'Cartier Sterling Silver Double C de Cartier Cufflinks',
		slug: toSlug('Cartier Sterling Silver Double C de Cartier Cufflinks'),
		category: 'Cufflinks',
		brand: 'Cartier',
		images: [
			'/images/p68-1.avif',
			'/images/p68-2.avif',
			'/images/p68-3.avif',
			'/images/p68-4.avif',
		],
		tags: ['todays-deal'],
		isPublished: true,
		price: 179.99,
		listPrice: 349.99,
		avgRating: 3.46,
		numReviews: 13,
		ratingDistribution: [
			{ rating: 1, count: 1 },
			{ rating: 2, count: 2 },
			{ rating: 3, count: 3 },
			{ rating: 4, count: 4 },
			{ rating: 5, count: 3 },
		],
		countInStock: 26,
		numSales: 58,
		description:
			"Cartier has earned a reputation for high-quality craftsmanship when it comes to fine objects and the Double C de Cartier cufflinks prove why. They're rendered in sterling silver and adorned with a powerful Double C motif; simply clip them onto your cuffs at your next formal event and enjoy compliments all evening long.",
		sizes: ['Standard'],
		colors: ['Silver'],

		reviews: [],
	},
	{
		name: 'Tateossian Rose Gold-Plated Square Gear Cufflinks',
		slug: toSlug('Tateossian Rose Gold-Plated Square Gear Cufflinks'),
		category: 'Cufflinks',
		brand: 'Tateossian',
		images: [
			'/images/p69-1.avif',
			'/images/p69-2.avif',
			'/images/p69-3.webp',
			'/images/p69-4.webp',
			'/images/p69-5.avif',
		],
		tags: ['featured'],
		isPublished: true,
		price: 99.99,
		listPrice: 0,
		avgRating: 4.71,
		numReviews: 7,
		ratingDistribution: [
			{ rating: 1, count: 0 },
			{ rating: 2, count: 0 },
			{ rating: 3, count: 0 },
			{ rating: 4, count: 2 },
			{ rating: 5, count: 5 },
		],
		countInStock: 54,
		numSales: 21,
		description:
			'Tateossian’s Mechanical collection boasts signature designs inspired by motion and movement. Crafted from rose gold-plated stainless steel, the Square Gear cufflinks display these creative principles flawlessly. With coloured metal gears interlocked in a square frame, the pair makes for a sleek and eye-catching addition to your smart styling edit.',
		sizes: ['Standard'],
		colors: ['Gold'],

		reviews: [],
	},
]

// !!! Reviews
const reviews = [
	{
		rating: 1,
		title: 'Poor quality',
		comment:
			'Very disappointed. The item broke after just a few uses. Not worth the money.',
	},
	{
		rating: 2,
		title: 'Disappointed',
		comment:
			"Not as expected. The material feels cheap, and it didn't fit well. Wouldn't buy again.",
	},
	{
		rating: 2,
		title: 'Needs improvement',
		comment:
			"It looks nice but doesn't perform as expected. Wouldn't recommend without upgrades.",
	},
	{
		rating: 3,
		title: 'not bad',
		comment:
			'This product is decent, the quality is good but it could use some improvements in the details.',
	},
	{
		rating: 3,
		title: 'Okay, not great',
		comment:
			'It works, but not as well as I hoped. Quality is average and lacks some finishing.',
	},
	{
		rating: 3,
		title: 'Good product',
		comment:
			'This product is amazing, I love it! The quality is top notch, the material is comfortable and breathable.',
	},
	{
		rating: 4,
		title: 'Pretty good',
		comment:
			"Solid product! Great value for the price, but there's room for minor improvements.",
	},
	{
		rating: 4,
		title: 'Very satisfied',
		comment:
			'Good product! High quality and worth the price. Would consider buying again.',
	},
	{
		rating: 4,
		title: 'Absolutely love it!',
		comment:
			'Perfect in every way! The quality, design, and comfort exceeded all my expectations.',
	},
	{
		rating: 4,
		title: 'Exceeded expectations!',
		comment:
			'Fantastic product! High quality, feels durable, and performs well. Highly recommend!',
	},
	{
		rating: 5,
		title: 'Perfect purchase!',
		comment:
			"Couldn't be happier with this product. The quality is excellent, and it works flawlessly!",
	},
	{
		rating: 5,
		title: 'Highly recommend',
		comment:
			"Amazing product! Worth every penny, great design, and feels premium. I'm very satisfied.",
	},
	{
		rating: 5,
		title: 'Just what I needed',
		comment:
			'Exactly as described! Quality exceeded my expectations, and it arrived quickly.',
	},
	{
		rating: 5,
		title: 'Excellent choice!',
		comment:
			'This product is outstanding! Everything about it feels top-notch, from material to functionality.',
	},
	{
		rating: 5,
		title: "Couldn't ask for more!",
		comment:
			"Love this product! It's durable, stylish, and works great. Would buy again without hesitation.",
	},
]

const data: Data = {
	users,
	products,
	reviews,
	webPages: [
		{
			title: 'About Us',
			slug: 'about-us',
			content: `This project is a fictional e-commerce demonstration application created for educational and portfolio purposes only. It is NOT affiliated with, endorsed by, or connected to Amazon or any other real company.

Welcome to Caeser Store, your trusted destination for quality products and exceptional service. Our journey began with a mission to bring you the best shopping experience by offering a wide range of products at competitive prices, all in one convenient platform.

At Caeser Store, we prioritize customer satisfaction and innovation. Our team works tirelessly to curate a diverse selection of items, from everyday essentials to exclusive deals, ensuring there's something for everyone. We also strive to make your shopping experience seamless with fast shipping, secure payments, and excellent customer support.

As we continue to grow, our commitment to quality and service remains unwavering. Thank you for choosing Caeser Store we look forward to being a part of your journey and delivering value every step of the way.`,
			isPublished: true,
		},
		{
			title: 'Contact Us',
			slug: 'contact-us',
			content: `This project is a fictional e-commerce demonstration application created for educational and portfolio purposes only. It is NOT affiliated with, endorsed by, or connected to Amazon or any other real company.

We're here to help! If you have any questions, concerns, or feedback, please don't hesitate to reach out to us. Our team is ready to assist you and ensure you have the best shopping experience.

**Customer Support**
For inquiries about orders, products, or account-related issues, contact our customer support team:
- **Email:** caeserlondon@gmail.com
- **Phone:** +44 078 6886 3113
- **Live Chat:** Available on our website from 9 AM to 6 PM (Monday to Friday).

**Head Office**
For corporate or business-related inquiries, reach out to our headquarters:
- **Address:** 1234 E-Commerce St, Suite 567, London, UK.
- **Phone:** +44 078 6886 3113
- **Email:** caeserlondon@gmail.com

We look forward to assisting you! Your satisfaction is our priority.`,
			isPublished: true,
		},
		{
			title: 'Help',
			slug: 'help',
			content: `This project is a fictional e-commerce demonstration application created for educational and portfolio purposes only. It is NOT affiliated with, endorsed by, or connected to Amazon or any other real company.

Welcome to our Help Center! We're here to assist you with any questions or concerns you may have while shopping with us. Whether you need help with orders, account management, or product inquiries, this page provides all the information you need to navigate our platform with ease.

**Placing and Managing Orders**
Placing an order is simple and secure. Browse our product categories, add items to your cart, and proceed to checkout. Once your order is placed, you can track its status through your account under the "My Orders" section. If you need to modify or cancel your order, please contact us as soon as possible for assistance.

**Shipping and Returns**
We offer a variety of shipping options to suit your needs, including standard and express delivery. For detailed shipping costs and delivery timelines, visit our Shipping Policy page. If you're not satisfied with your purchase, our hassle-free return process allows you to initiate a return within the specified timeframe. Check our Returns Policy for more details.

**Account and Support**
Managing your account is easy. Log in to update your personal information, payment methods, and saved addresses. If you encounter any issues or need further assistance, our customer support team is available via email, live chat, or phone. Visit our Contact Us page for support hours and contact details.`,
			isPublished: true,
		},
		{
			title: 'Privacy Policy',
			slug: 'privacy-policy',
			content: `This project is a fictional e-commerce demonstration application created for educational and portfolio purposes only. It is NOT affiliated with, endorsed by, or connected to Amazon or any other real company.

We value your privacy and are committed to protecting your personal information. This Privacy Notice explains how we collect, use, and share your data when you interact with our services. By using our platform, you consent to the practices described herein.

We collect data such as your name, email address, and payment details to provide you with tailored services and improve your experience. This information may also be used for marketing purposes, but only with your consent. Additionally, we may share your data with trusted third-party providers to facilitate transactions or deliver products.

Your data is safeguarded through robust security measures to prevent unauthorized access. However, you have the right to access, correct, or delete your personal information at any time. For inquiries or concerns regarding your privacy, please contact our support team.`,
			isPublished: true,
		},
		{
			title: 'Conditions of Use',
			slug: 'conditions-of-use',
			content: `This project is a fictional e-commerce demonstration application created for educational and portfolio purposes only. It is NOT affiliated with, endorsed by, or connected to Amazon or any other real company.

Welcome to Caeser Store!. By accessing or using our website, you agree to comply with and be bound by the following terms and conditions. These terms govern your use of our platform, including browsing, purchasing products, and interacting with any content or services provided. You must be at least 18 years old or have the consent of a parent or guardian to use this website. Any breach of these terms may result in the termination of your access to our platform.

We strive to ensure all product descriptions, pricing, and availability information on our website are accurate. However, errors may occur, and we reserve the right to correct them without prior notice. All purchases are subject to our return and refund policy. By using our site, you acknowledge that your personal information will be processed according to our privacy policy, ensuring your data is handled securely and responsibly. Please review these terms carefully before proceeding with any transactions.`,
			isPublished: true,
		},
		{
			title: 'Customer Service',
			slug: 'customer-service',
			content: `This project is a fictional e-commerce demonstration application created for educational and portfolio purposes only. It is NOT affiliated with, endorsed by, or connected to Amazon or any other real company.

At Caeser Store, our customer service team is here to ensure you have the best shopping experience. Whether you need assistance with orders, product details, or returns, we are committed to providing prompt and helpful support.

If you have questions or concerns, please reach out to us through our multiple contact options:
- **Email:** caeserlondon@gmail
- **Phone:** +44 078 6886 3113
- **Live Chat:** Available on our website for instant assistance

We also provide helpful resources such as order tracking, product guides, and FAQs to assist you with common inquiries. Your satisfaction is our priority, and we're here to resolve any issues quickly and efficiently. Thank you for choosing us!`,
			isPublished: true,
		},
		{
			title: 'Returns Policy',
			slug: 'returns-policy',
			content: 'Returns Policy Content',
			isPublished: true,
		},
		{
			title: 'Careers',
			slug: 'careers',
			content: 'careers Content',
			isPublished: true,
		},
		{
			title: 'Blog',
			slug: 'blog',
			content: 'Blog Content',
			isPublished: true,
		},
		{
			title: 'Sell Products',
			slug: 'sell',
			content: 'Sell Products Content',
			isPublished: true,
		},
		{
			title: 'Become Affiliate',
			slug: 'become-affiliate',
			content: 'Become Affiliate Content',
			isPublished: true,
		},
		{
			title: 'Advertise Your Products',
			slug: 'advertise',
			content: 'Advertise Your Products',
			isPublished: true,
		},
		{
			title: 'Shipping Rates & Policies',
			slug: 'shipping',
			content: 'Shipping Rates & Policies',
			isPublished: true,
		},
	],
	headerMenus: [
		{
			name: "Today's Deal",
			href: '/search?tag=todays-deal',
		},
		{
			name: 'New Arrivals',
			href: '/search?tag=new-arrival',
		},
		{
			name: 'Featured Products',
			href: '/search?tag=featured',
		},
		{
			name: 'Best Sellers',
			href: '/search?tag=best-seller',
		},
		{
			name: 'Browsing History',
			href: '/#browsing-history',
		},
		{
			name: 'Customer Service',
			href: '/page/customer-service',
		},
		{
			name: 'About Us',
			href: '/page/about-us',
		},
		{
			name: 'Help',
			href: '/page/help',
		},
	],
	carousels: [
		{
			// !1 carousel - New Arrivals
			title: 'Discover Our Most Fashionable New Arrivals',
			buttonCaption: 'Shop Now',
			image: '/images/banner1.jpg',
			url: '/search?tag=new-arrival',
			isPublished: true,
		},
		{
			// !2 carousel - Cufflinks Collection
			title: 'Elevate Your Style with Exquisite Cufflinks',
			buttonCaption: 'See More',
			image: '/images/banner2.jpg',
			url: '/search?q=all&category=Cufflinks&tag=all&price=all&rating=all&sort=best-selling&page=1',
			isPublished: true,
		},
		{
			// !3 carousel - Wrist Watches
			title: 'Explore the Finest Collection of Wrist Watches',
			buttonCaption: 'See More',
			image: '/images/banner3.jpg',
			url: '/search?q=all&category=Wrist+Watches&tag=all&price=all&rating=all&sort=best-selling&page=1',
			isPublished: true,
		},
	],
	settings: [
		{
			common: {
				freeShippingMinPrice: 35,
				isMaintenanceMode: false,
				defaultTheme: 'Light',
				defaultColor: 'Gold',
				pageSize: 9,
			},
			site: {
				name: 'Caeser Store',
				description:
					'Caeser Store is a sample Ecommerce website built with Next.js, Tailwind CSS, and MongoDB.',
				keywords: 'Next Ecommerce, Next.js, Tailwind CSS, MongoDB',
				url: 'https://caeser-store.vercel.app',
				logo: '/icons/logo.png',
				slogan: 'Beyond Fashion. Pure Luxury.',
				author: 'Caeser Store',
				copyright:
					'2019-2026  Caeser Store Inc. and its fictional affiliates. All rights reserved.',
				email: 'caeserlondon@gmail.com',
				address: '123, Caeser Street, Hyde Park, London W2 2UH',
				phone: '+44 07868863113',
			},
			carousels: [
				{
					// !1 carousel - New Arrivals
					title: 'Discover Our Most Fashionable New Arrivals',
					buttonCaption: 'Shop Now',
					image: '/images/banner1.jpg',
					url: '/search?tag=new-arrival',
				},
				{
					// !2 carousel - Cufflinks Collection
					title: 'Elevate Your Style with Exquisite Cufflinks',
					buttonCaption: 'See More',
					image: '/images/banner2.jpg',
					url: '/search?q=all&category=Cufflinks&tag=all&price=all&rating=all&sort=best-selling&page=1',
				},
				{
					// !3 carousel - Wrist Watches
					title: 'Explore the Finest Collection of Wrist Watches',
					buttonCaption: 'See More',
					image: '/images/banner3.jpg',
					url: '/search?q=all&category=Wrist+Watches&tag=all&price=all&rating=all&sort=best-selling&page=1',
				},
			],
			availableLanguages: i18n.locales.map((locale) => ({
				code: locale.code,
				name: locale.name,
			})),
			defaultLanguage: 'en',
			availableCurrencies: [
				{
					name: 'British Pound',
					code: 'GBP',
					symbol: '£',
					convertRate: 1,
				},
				{
					name: 'United States Dollar',
					code: 'USD',
					symbol: '$',
					convertRate: 1.27,
				},
				{
					name: 'Euro',
					code: 'EUR',
					symbol: '€',
					convertRate: 1.17,
				},
				{
					name: 'UAE Dirham',
					code: 'AED',
					symbol: 'AED',
					convertRate: 4.65,
				},
			],
			defaultCurrency: 'GBP',
			availablePaymentMethods: [
				{ name: 'PayPal', commission: 0 },
				{ name: 'Stripe', commission: 0 },
				{ name: 'Cash On Delivery', commission: 0 },
			],
			defaultPaymentMethod: 'PayPal',
			availableDeliveryDates: [
				{
					name: 'Tomorrow',
					daysToDeliver: 1,
					shippingPrice: 12.9,
					freeShippingMinPrice: 0,
				},
				{
					name: 'Next 3 Days',
					daysToDeliver: 3,
					shippingPrice: 6.9,
					freeShippingMinPrice: 0,
				},
				{
					name: 'Next 5 Days',
					daysToDeliver: 5,
					shippingPrice: 4.9,
					freeShippingMinPrice: 35,
				},
			],
			defaultDeliveryDate: 'Next 5 Days',
		},
	],
}

export default data
